image: docker.io/erickweeds/api-rest-vanilla-php:latest

before_script:
  - apt-get update -yq
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - ./vendor/bin/phpunit tests/ --testdox

deploy:
  stage: deploy
  image: ruby:latest
  environment:
    name: production
  script:
    - composer install --no-progress --prefer-dist
    - gem install dpl
    - echo "Attempting to deploy to production server"
    - dpl --provider=heroku --app=$HEROKU_APP_SINGLE_ENV --api-key=$HEROKU_API_KEY
  when: manual
  only:
    - master
